mongo:
  image: 'mongo:3'
  ports:
    - '27017:27017'
  expose:
    - "27017"

redis:
  image: 'redis:3'
  expose:
    - '6379'

web:
  image: 'my-hub-decathlon:latest'
  links:
    - mongo
    - redis
  volumes:
    - ./:/tapiriik:rw
  ports:
    - '8000:8000'
  env_file: environment