mongo:
  image: 'mongo:3'
  expose:
    - '27017'

RMQ:
  image: 'rabbitmq:3'
  environment:
    - RABBITMQ_NODENAME=tapiriik
  expose:
    - '5672'

redis:
  image: 'redis:3'
  expose:
    - '6379'

web:
  image: 'my-hub-decathlon:latest'
  links:
    - mongo
    - RMQ
    - redis
  volumes:
    - ./:/tapiriik:rw
  ports:
    - '8000:8000'
  env_file: environment